version: '2'

services:

  client:
    build:
      dockerfile: Dockerfile.client
      context: .
    volumes:
      - .:/usr/src/app
    stdin_open: true
    tty: true
    networks:
      - back
    environment:
      - LEIN_REPL_PORT=40001
      - LEIN_REPL_HOST=0.0.0.0
    ports:
      - "0.0.0.0:40001:40001"

networks:
  back:
    driver: bridge
